<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="/signUp" method="post">
    <input name="email" type="email" placeholder="EMAIL">
    <input name="password" type="password" placeholder="PASSWORD">
    <input name="firstname" type="text" placeholder="FIRSTNAME">
    <input name="lastname" type="text" placeholder="LASTNAME">
    <input name="phone" type="text" placeholder="PHONE">
    <input type="submit" value="SIGN UP">
</form>
</body>
</html>